### ISSUE TITLE
Build Arguments for DockerBuildTask

### ISSUE THREAD

**Issue by gamma** [gesellix/gradle-docker-plugin#134]
I haven't found a hint on how to add build arguments to the DockerBuildTask. Specifically I want to add `--build-arg constraint:ostype==linux` since my endpoint supports both, windows and linux.

Can you please point me into the correct direction?

**Comment by gesellix** [comment]
There's no dedicated task parameter (yet). If you have a quick look at the [api documentation](https://docs.docker.com/engine/api/v1.41/#operation/ImageBuild), you'll see the relevant _query_ parameter `buildargs`, which expects a JSON encoded Map. So, you have to use the `buildParams` property of the DockerBuildTask like this:

```
task buildExample(type: DockerBuildTask) {
   // ... (other build task parameters) ...

   Map<String, Object> buildargs = new HashMap<>()
   buildargs.put("constraint", "ostype==linux")
   buildParams.put("buildargs", buildargs)
}
```

**Comment by gamma** [comment]
Thanks very much! 👍
