### ISSUE TITLE
Logfile from container

### ISSUE THREAD

**Issue by gamma** [gesellix/gradle-docker-plugin#135]
I'm using this cradle-docker-plugin for several years now, but I'm missing the `log` command to fetch the containers output for local storage.

It'd be great to have it added.

**Comment by gesellix** [comment]
Would you like to create a pull request, maybe only a draft? Fetching logs (without "following" them) should be quite simple to implement. You might simply copy/paste from similar tasks like `DockerRestartTask`.

I won't promise any time range, maybe I'll find some free time to implement it myself, maybe you're faster :)

**Comment by gamma** [comment]
I had a look into the api and tried an ad-hoc task in my gradle script, which did not work out.

I'll check an implementation when I find some time for it in the next week. Shouldn't be too hard 🤣

Thanks for the heads up.

**Comment by gesellix** [comment]
Hey @gamma, I've just merged a new `DockerLogsTask`, but cannot cut a release just yet. If you don't want to wait for a proper release, you may build the plugin locally, based on the current `main` branch.

**Comment by gesellix** [comment]
The plugin containing the log task has been released: https://plugins.gradle.org/plugin/de.gesellix.docker/2022-01-29T20-50-00
