### ISSUE TITLE
implement DockerExecTask

### ISSUE THREAD

**Issue by germanSancho** [gesellix/gradle-docker-plugin#20]
It would be nice to be able to execute a command (i.e, `docker exec`) inside a running container, in a non-interactive way (at least at first). The DSL could look like this:

``` groovy
task execFoo(type: DockerExecTask) {
  containerId = 'foo'
  commandLine = 'touch /tmp/foo.txt'
}
```

**Comment by germanSancho** [comment]
works great, thank you very much!

**Comment by gesellix** [comment]
@germanSancho great, thanks for your feedback! :)
