### ISSUE TITLE
Using -v for run command in order to mount to the host system

### ISSUE THREAD

**Issue by schmidthappens** [gesellix/gradle-docker-plugin#244]
Hi @gesellix,

is it possible to add additional options to the `run`-task like `-v`?
What I would like to achieve is to let a container start where some tests using Testcontainer will run. Therefore I need to make something like this

`docker run -v /var/run/docker.sock:/var/run/docker.sock -ti someimage:latest`

**Comment by gesellix** [comment]
Hey @schmidthappens :)

yes that should be possible using the HostConfig like in the example at https://github.com/gesellix/gradle-docker-plugin-example/blob/bba3cd8a224625e1a0134bfb940fd485f8f0f2fc/run-with-data-volume/build.gradle.kts#L19

I'm aware that the syntax might feel clunky (it's the bare Docker api), but it should work just like the cli `--volume` option. Please leave some feedback if this is not working as expected.

**Comment by schmidthappens** [comment]
Works like a charm ❤️ Thank you

![ty](https://user-images.githubusercontent.com/57909250/180400369-cad52de6-7ac1-41d7-95e1-5ffd166a5a11.gif)

**Comment by gesellix** [comment]
Great :)
