### ISSUE TITLE
Dispose Task should fail silently if Image is still in use

### ISSUE THREAD

**Issue by sgrell** [gesellix/gradle-docker-plugin#268]
We currently have the problem that we are using the same image in multiple tasks that run in parallel. The container names are unique but they are using the same image. So when the dispose task is executed `docker rm` is successful but `docker rmi` fails because the image is still in use. We get an exception with `409 Conflict`.

The problem is line 76 in [DockerDisposeContainerTask](https://github.com/gesellix/gradle-docker-plugin/blob/3436ee471930ae9c2ca03b52925d556eb63d9253/plugin/src/main/java/de/gesellix/gradle/docker/tasks/DockerDisposeContainerTask.java#L76)

It is possible to set `rmiParentImage` to `false`, however that would mean, that we never cleanup the images, which is not our preferred solution.

Is it possible to add an option to ignore errors or at least these Conflict-errors?

**Comment by gesellix** [comment]
Released with https://github.com/gesellix/gradle-docker-plugin/releases/tag/v2022-12-06T08-00-00 :)

**Comment by sgrell** [comment]
thank you so much, I was just about to get started with it, when I saw that you already fixed it 😄

**Comment by gesellix** [comment]
Yeah, couldn't keep my hands off it :)
If anything is still missing, just leave a note!
