### ISSUE TITLE
Comments about DockerPlugin.groovy

### ISSUE THREAD

**Issue by ysb33r** [gesellix/gradle-docker-plugin#39]
I would like to make some points regarding the block of code that is around https://github.com/gesellix/gradle-docker-plugin/blob/master/src/main/groovy/de/gesellix/gradle/docker/DockerPlugin.groovy#L22

1. Use of `withType` will only work if the tasks already exist at that point. It is usually combined with a `whenTaskAdded`.
2. Pushing defaults from an extension into a task is not good practice. It is better for the task to pull values from the extension. This can either be achieved via conventions or simply within the getXYZ method for a task attribute XYZ. This would require annotating getters rather than properties in the task, but it results in better experience for the scirpt author. (More details on this can be found at http://www.slideshare.net/ysb33r/idiomatic-gradle-plugin-writing-56121903).

**Comment by gesellix** [comment]
1. you mean, it's a simple "replace `withType` with `whenTaskAdded`"?
2. I thought conventions were internal or deprecated api, but I'll have a look into it.

Thanks for the heads-up!

**Comment by ysb33r** [comment]
>  you mean, it's a simple "replace withType with whenTaskAdded"?

You need both - the one acts upon tasks that already exist, the other triggers when tasks are added. The type, however has to be exact - inheritance does not count. For instance if `VersionTask` inherits from `DockerTask`, and your trigger is only for `DockerTask`, adding a new `VersionTask` will not invoke the action. (unless this behaviour has changed recently, this is my understanding).
 
 >   I thought conventions were internal or deprecated api, but I'll have a look into it.

I thought is was deprecated too, but I have this question on the Gradle forum and I was told that is an internal API, but it is not deprecated. It is one way of achieving certain behaviour, although in a number of cases I found better ways to achive what I wanted without resorting to it.

**Comment by gesellix** [comment]
Alright, good to learn something new!

Closing after https://github.com/ysb33r/gradle-docker-plugin/commit/7c12d31e8d452c5ab304ecbd3588fc363802d6c4 has been merged.
