### ISSUE TITLE
Comments about DockerBuildTask

### ISSUE THREAD

**Issue by ysb33r** [gesellix/gradle-docker-plugin#45]
Whilst working with an instance of this task I came across some style things.

**buildContextDirectory**: I wanted to do

``` groovy
buildContextDirectory = { "${buildDir}/foo" }
```

however it forces me to create a `File` object either via `file` or `new File`. A better style for scalar `File` properties is to do.

``` groovy
def buildContextDirectory

@InputDirectory
File getBuildContextDirectory() {
  project.file(this.buildContextDirectory}
}
```

This approach allows for lazy evaluation as in my example above where I might have wanted to delay the setting of `buildDir`.

**targetFile**: It is better to have this annotated as it allows Gradle to check whether the output has been deleted and thus automatically set the task as out of date.

``` groovy
@OutputFile
File getTargetFile() {
  // We can get away with lazy initialisation as currently this is not concurrent in Gradle
  if(!this.targetFile) {
    this.targetFile = new File(temporaryDir, "buildContext_${normalizedImageName}.tar.gz")
  }
  this.targetFile
}

private File targetFile
```

Some more tips here -> http://www.slideshare.net/ysb33r/idiomatic-gradle-plugin-writing-56121903

**Comment by gesellix** [comment]
alright, I'll apply the proposed changes - similar style improvements are certainly possible in the other tasks... thanks for the heads-up!

**Comment by gesellix** [comment]
Closing, some patterns have been applied - more to come.
