### ISSUE TITLE
Setting environment for DockerContainerTask

### ISSUE THREAD

**Issue by ysb33r** [gesellix/gradle-docker-plugin#47]
This might apply elsewhere, but I came across it whilst specifying the environment. Currently one has to 
do 

``` groovy
env = [ 'foo1=bar1', 'foo2=bar2' ]
```

It would be more idiomatic to be able to be able to do

``` groovy
env foo1 : 'bar1
env foo2 : 'bar2', foo3 : 'bar3'
```

The three slides starting here http://www.slideshare.net/ysb33r/idiomatic-gradle-plugin-writing-56121903/16?src=clipshare are from I've written about this kind of approach before. If I get time, before you do I might create a PR for this.

**Comment by gesellix** [comment]
The `DockerContainerTask` is being removed with the next release.
