### ISSUE TITLE
Running DockerContainerTask as specific user

### ISSUE THREAD

**Issue by adamjmarkham** [gesellix/gradle-docker-plugin#49]
Great plugin, but I have come across this issue i'm not able to get past.

I want to specify the user to run a DockerContainerTask as. On OS X from gradle it seems to run as a "daemon" user. I'm running gradle as this user "adammarkham"

On the command line I would do something like: `docker run -uroot`

Is there an equivalent config I can use in the DockerContainerTask?

**Comment by gesellix** [comment]
Thanks!

Can you explain in detail on which side you'd like to set the user? The `docker run -u <user>` parameter specifies the user _inside_ the container. This means that it is irrelevant under which user Gradle is running and it doesn't matter whether Gradle runs in daemon mode or in the foreground.

If you want to specifiy the user inside the container, there's currently no option available in the `DockerContainerTask`. I'd suggest to use a Dockerfile like below to achieve the same result:

````
FROM alpine:edge
RUN adduser -S myuser
USER myuser
CMD ["id"]
````

You can find another example how to run a container using the more low level tasks at https://github.com/gesellix/gradle-docker-plugin-example/tree/master/run-with-user, and it can be run with `./gradlew :run-with-user:printContainerLogs`. The example shows how to manually override the user even if it was defined inside the Dockerfile.

Did that help?

**Comment by gesellix** [comment]
@adamjmarkham do you still have the described issue?

**Comment by gesellix** [comment]
@adamjmarkham closing now due to missing feedback. Feel free to add further comments.
