### ISSUE TITLE
How to delete a docker volume when stop/delete a container?

### ISSUE THREAD

**Issue by pedrro** [gesellix/gradle-docker-plugin#52]
Hey guys, I'm using that plugin in a large scale application, but I'm having problems with volume, unfortunately, when I execute the dockerRmTask or DockerStopTask, it's not deleting the volumes of containers.

Exist some way to do that or it's like a feature request for the plugin?

**Comment by gesellix** [comment]
Hi, the volumes won't automatically removed (just to be safe). There's also no convenient task to help you with that (see https://github.com/gesellix/gradle-docker-plugin/blob/master/roadmap.md#volumes).
So the answer is: it's a feature request :-)

I would need some more details: do you create your volumes by creating volume containers?

**Comment by pedrro** [comment]
Yes, every time that a container is created, also a volume is create for this container, the problem is that when a container is deleted, isn't deleting the volume, so, is add a lot of space to my hard disk :D 

The command that I run to remove the containers is: `docker volume rm $(docker volume ls -qf dangling=true)`

**Comment by gesellix** [comment]
Are you fancy to give some quick hack a try?
I added some new tasks to the newly published version `2016-06-20T23-19-27` (https://plugins.gradle.org/plugin/de.gesellix.docker).

The integration test at https://github.com/gesellix/gradle-docker-plugin/blob/master/src/integrationTest/groovy/de/gesellix/gradle/docker/DockerPluginIntegrationTest.groovy#L306 should show you how to manage volumes without data-containers.

The more generic cleanup you mentioned should now also be possible by adding a query to the "volume ls" task:

````
task danglingVolumes(task: DockerVolumesTask) {
    query = [filters: [dangling: ["true"]]]
}
task rmDanglingVolumes(task: DockerTask) {
    dependsOn danglingVolumes
    doLast {
        danglingVolumes.content.each {
            getDockerClient().rmVolume(it)
        }
    }
}
````

**Comment by gesellix** [comment]
a side note: there's already a `DockerCleanupTask`, which removes all stopped containers, and dangling images. Would you like it to also remove dangling volumes?

**Comment by gesellix** [comment]
I renamed both new tasks to be more consistent with the other ones. Please use the new release `2016-06-21T00-41-11`.

**Comment by pedrro** [comment]
> a side note: there's already a DockerCleanupTask, which removes all stopped containers, and dangling images. Would you like it to also remove dangling volumes?

I think that this is the best approach for the application, could you do that?

**Comment by gesellix** [comment]
Yes, with the most [recent version](https://plugins.gradle.org/plugin/de.gesellix.docker) of the plugin you can cleanup exited containers, dangling images, and optionally dangling volumes.

See https://github.com/gesellix/gradle-docker-plugin-example/blob/5503a4864d48f002e9d0449a552f8e0acb8e1ff3/build.gradle#L56 for an example. It only logs container and volume candidates for a deletion, but actually only removes dangling images. The closures need to return false for entries you'd like to remove.

Please give it a try and leave some feedback here!

**Comment by pedrro** [comment]
Awesome, I'll take a look on that and bring some feedback! Thanks @gesellix

**Comment by pedrro** [comment]
Hi @gesellix, I tried the same function that u used on example, but passing false to **shouldKeepVolume** variable and I'm getting the following error: 
`request failed: 'get null: no such volume`

Below an example of volume output that I had on the task:
`volume : [Driver:local, Labels:null, Mountpoint:/var/lib/docker/volumes/a40f66dd58edc05d6cb096871abd8750ad8a683c6ae1987e68982d7f46e26855/_data, Name:a40f66dd58edc05d6cb096871abd8750ad8a683c6ae1987e68982d7f46e26855]
`

I'm trying to debug here, could u take a look on this error?

**Comment by pedrro** [comment]
Now, I changed the task a little to:
```
task cleanupStorage(type: DockerCleanupTask) {
    shouldKeepContainer = false
    shouldKeepVolume = false
}
```

The task now is passing, but not removing volumes

**Comment by gesellix** [comment]
Can you run the last example with an additional `--info` on the command line? It should then show detailed output of which docker actions are called. If any.

**Comment by pedrro** [comment]
@gesellix here the outputs:
```
Executing task ':cleanupStorage' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
docker cleanup
docker ps
using docker at 'unix:///var/run/docker.sock'
docker images
docker volume ls
:cleanupStorage (Thread[Daemon worker Thread 3,5,main]) completed. Took 0.347 secs.
```

**Comment by pedrro** [comment]
Now printing the volumes:

```
:cleanupStorage
Executing task ':cleanupStorage' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
docker cleanup
docker ps
using docker at 'unix:///var/run/docker.sock'
docker images
docker volume ls
volume : [Driver:local, Labels:null, Mountpoint:/var/lib/docker/volumes/3594ce3fe3c89c6f13024efb39e9e54904462f3fd4122877cb8f895b32451277/_data, Name:3594ce3fe3c89c6f13024efb39e9e54904462f3fd4122877cb8f895b32451277]
**docker volume rm**
request failed: 'get null: no such volume
'
:cleanupStorage FAILED
:cleanupStorage (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.503 secs.

```

Looks like it isn't passing the id of volume to docker command.

**Comment by gesellix** [comment]
ok, thanks - I'll try to reproduce it on my machine. Can you check the output of `docker volume ls`, please? the `3594ce3fe3c` volume should appear there. Then, you can also get more details with `docker volume inspect 3594ce3fe3c`. The last command would help me to create a similar volume locally.

**Comment by pedrro** [comment]
Strange, the volume appear on docker volume ls, but, when I use the inspect, I got the error *no such volume*

**Comment by gesellix** [comment]
now we're talking ;-)

**Comment by gesellix** [comment]
ok, let's dig deeper: are you on Linux or on Mac? If Mac, using xhyve or Machine/VirtualBox?

**Comment by pedrro** [comment]
Mac, using docker for mac beta

**Comment by pedrro** [comment]
So, I deleted all the dangling volumes and put another container to run and I got the same error.

```
:cleanupStorage
Executing task ':cleanupStorage' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
docker cleanup
docker ps
using docker at 'unix:///var/run/docker.sock'
container : [Command:/entrypoint.sh mongod, Created:1466707216, HostConfig:[NetworkMode:default], Id:610b624cd2e138524ed36ff9e2a3fb3302489194e866fe3a3ce3168270c45747, Image:mongo:3.2.1, ImageID:sha256:7e350b877a9a5c3cc570c3b7d0dffff4165dc8eac749f50710a193b04fd3cfcd, Labels:[:], Mounts:[[Destination:/data/configdb, Driver:local, Mode:, Name:7d7dd5fb8ddc12329cea5460bbe63d678bfaa3e1fbc7c41ccc36a6a5f2319611, Propagation:, RW:true, Source:/var/lib/docker/volumes/7d7dd5fb8ddc12329cea5460bbe63d678bfaa3e1fbc7c41ccc36a6a5f2319611/_data], [Destination:/data/db, Driver:local, Mode:, Name:8035a0243df6075189ecbd2c97080d04319b16220c85f51815f2b621265d525b, Propagation:, RW:true, Source:/var/lib/docker/volumes/8035a0243df6075189ecbd2c97080d04319b16220c85f51815f2b621265d525b/_data]], Names:[/mongo], NetworkSettings:[Networks:[bridge:[Aliases:null, EndpointID:, Gateway:, GlobalIPv6Address:, GlobalIPv6PrefixLen:0, IPAMConfig:null, IPAddress:, IPPrefixLen:0, IPv6Gateway:, Links:null, MacAddress:, NetworkID:]]], Ports:[], State:exited, Status:Exited (137) 6 seconds ago]
docker rm
docker images
docker volume ls
volume : [Driver:local, Labels:null, Mountpoint:/var/lib/docker/volumes/8035a0243df6075189ecbd2c97080d04319b16220c85f51815f2b621265d525b/_data, Name:8035a0243df6075189ecbd2c97080d04319b16220c85f51815f2b621265d525b]
volume : [Driver:local, Labels:null, Mountpoint:/var/lib/docker/volumes/fd78552134996b48639d3b77ef2a9f104911091b01d44b5e6e39c36df123ff1a/_data, Name:fd78552134996b48639d3b77ef2a9f104911091b01d44b5e6e39c36df123ff1a]
volume : [Driver:local, Labels:null, Mountpoint:/var/lib/docker/volumes/7d7dd5fb8ddc12329cea5460bbe63d678bfaa3e1fbc7c41ccc36a6a5f2319611/_data, Name:7d7dd5fb8ddc12329cea5460bbe63d678bfaa3e1fbc7c41ccc36a6a5f2319611]
docker volume rm
request failed: 'get null: no such volume'

```

**Comment by gesellix** [comment]
can you post the container creation commands?

**Comment by pedrro** [comment]
```
task startDockerMongo(type: DockerContainerTask) {
    image = "mongo:3.2.1"
    containerName = MONGO_CONTAINER_ID
    targetState = DockerContainerTask.State.RELOADED
    ports = ["27017:27017"]
}
```

**Comment by gesellix** [comment]
thanks, I'll try to reproduce...

**Comment by gesellix** [comment]
next one: can you print the output of this: `docker inspect  -f "{{json .Mounts }}" MONGO_CONTAINER_ID`? The volume id in question should appear there.

**Comment by gesellix** [comment]
I assume the Mongo container is still running when you're trying to cleanup your storage, correct? In other words: the volume shouldn't be considered to be dangling. Maybe it's not one of the Mongo container volumes.

**Comment by gesellix** [comment]
maybe it helps to show the debug output with `--debug`. then we'll see the failing request including the volume id.

**Comment by gesellix** [comment]
ah, now I also have it reproduced. investigating...

**Comment by pedrro** [comment]
Output of **docker inspect -f "{{json .Mounts }}"** 
```
[
  {
    "Name": "7c7600478c091546529563266d735f673a3e6c052805412c493e75b1fef9386d",
    "Source": "/var/lib/docker/volumes/7c7600478c091546529563266d735f673a3e6c052805412c493e75b1fef9386d/_data",
    "Destination": "/data/configdb",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  },
  {
    "Name": "e7c5c40db45a244b87f717d85618e01f2d96bed836394e22a0606a429e311d63",
    "Source": "/var/lib/docker/volumes/e7c5c40db45a244b87f717d85618e01f2d96bed836394e22a0606a429e311d63/_data",
    "Destination": "/data/db",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  }
]
```

When I tried  to run the task, the container was not running...

**Comment by gesellix** [comment]
ok, I found it. my bad... I'll ping you when the release train reaches the plugin portal.

**Comment by gesellix** [comment]
please use the current release `2016-06-23T21-39-11`. It should now work as expected.

a little background: the plugin tried to delete a volume by its `Id`. Sadly, volumes only have `Name`, which is why it tried to remove a volume named `null`.

**Comment by pedrro** [comment]
Awesome job @gesellix, now is working, thanks for all support provided!

**Comment by gesellix** [comment]
thanks for your patience @pedrro!
