### ISSUE TITLE
Plugin doesn't work with "Docker for Mac"

### ISSUE THREAD

**Issue by imshashank** [gesellix/gradle-docker-plugin#54]
I upgraded to docker for mac and getting this error->

```
Execution failed for task ':application:c.....:stopContainer'.
> java.io.FileNotFoundException: unix://socket/containers/....
```

Do u know what I need to change to make this work with Docker for Mac ?

**Comment by gesellix** [comment]
The part with `unix://socket/containers...` looks surprising to me, on a default installation it should look like `unix://var/run/docker.sock`:

- did you try the most recent plugin release?
- is your `DOCKER_HOST` environment variable set? It shouldn't be set anymore under Docker for Mac.

To get more details, please run your task with `-i -s` and post the output with the error and stacktrace here.

**Comment by gesellix** [comment]
@imshashank did you make it work?

**Comment by pedrro** [comment]
I found a issue with plugin and new release of Docker for Mac, I'll bring more information.

**Comment by gesellix** [comment]
great thanks!

**Comment by gesellix** [comment]
closing due to missing feedback.

@imshashank please re-open if you have more details
@pedrro please file a new issue if you have another error
