### ISSUE TITLE
Plugin doesn't work if exists .docker folder without certs. It try uses https instead http

### ISSUE THREAD

**Issue by maratfdrv** [gesellix/gradle-docker-plugin#55]
Plugin doesn't understand empty DOCKER_TLS_VERIFY env variable.
Plugin understands  DOCKER_TLS_VERIFY = 0  but it this case console line tool tries to use default cert files.

system ubuntu 14.04 
log

01:55:14.251 [DEBUG] [de.gesellix.docker.client.protocolhandler.DockerURLHandler] dockerCertPath=/root/.docker
01:55:14.252 [DEBUG] [de.gesellix.docker.client.protocolhandler.DockerURLHandler] certsPathExists=true, isTlsPort=true
01:55:14.254 [DEBUG] [de.gesellix.docker.client.protocolhandler.DockerURLHandler] assume 'https'
01:55:14.256 [DEBUG] [de.gesellix.docker.client.protocolhandler.DockerURLHandler] selected dockerHost at 'https://localhost:2376'

**Comment by gesellix** [comment]
What do you expect? With `DOCKER_TLS_VERIFY = 0` you advice the tools to enable TLS, so they'll search for the certificates. It also seems like you're using a `DOCKER_HOST` with the TLS port 2376. Is the error that the plugin doesn't use the certs when `DOCKER_TLS_VERIFY = 0`?
Or do you expect the plugin to disable TLS when `DOCKER_TLS_VERIFY` is empty/missing _and_ the certs are missing?

**Comment by gesellix** [comment]
closing - please reopen when you have more details. Thanks!
