### ISSUE TITLE
Invalid name when using GString in docker run

### ISSUE THREAD

**Issue by schup** [gesellix/gradle-docker-plugin#58]
When using a dynamic string for the containerName of the DockerRunTask an invalid URL gets generated for the create. It seems like the GString is treated as an array of characters. 

Gradle version: 3.5
Gradle plugin version:  "2017-06-03T19-45-06"

Example:
```
task dockerRun(type: DockerRunTask, group: 'docker') {
	containerName = "${app.name}-${app.stage}-${app.version}"
```
leads to 
```
POST http://2f7661722f72756e2f646f636b65722e736f636b.socket/containers/create?name=d&name=e&name=m&name=o
```

Explicitly converting the GString to a string works around this problem.

```
task dockerRun(type: DockerRunTask, group: 'docker') {
	containerName = "${app.name}-${app.stage}-${app.version}".toString()
```

```
POST http://2f7661722f72756e2f646f636b65722e736f636b.socket/containers/create?name=demo
```

**Comment by gesellix** [comment]
Sorry for the delay... Please give the current release a try with version 2017-06-19T22-12-00 from https://plugins.gradle.org/plugin/de.gesellix.docker.

**Comment by schup** [comment]
Thanks Tobias,
I've tested with the new version and it's working now.

Thanks for the update.
