### ISSUE TITLE
DockerPublishTask and tagging

### ISSUE THREAD

**Issue by gamma** [gesellix/gradle-docker-plugin#59]
There seems to be an issue with tagging from a DockerPublishTask with the current version.

Up to now I was able to do the following:

    task buildImage(type: DockerPublishTask) {
        imageName = "my/image"
        imageTag = 'latest'
        buildContextDirectory = file('./docker/')
        targetRegistries = [
            dev: "registry:5000"
        ]
    }

It would now tag the image with: "registry:5000/my/image:latest"

The current version seems to not tag it with "registry:5000" - but push it anyway. My current workaround is to use the following definition:

    task buildImage(type: DockerPublishTask) {
        imageName = "registry:5000/my/image"
        imageTag = 'latest'
        buildContextDirectory = file('./docker/')
        targetRegistries = [
            dev: ""
        ]
    }

**Comment by gesellix** [comment]
The publish task only temporarily tags your images for publishing them to a registry. Afterwards, the registry specific tags will be removed. Are you only missing those temporary images, but the publish itself succeeded? If you want to keep those tags, you'll need to manually configure every step (build, tag, push) as dedicated task.

This example worked for me as expected:

    docker run --rm -dit -p 5000:5000 registry:2
    git clone https://github.com/gesellix/gradle-docker-plugin-example
    cd gradle-docker-plugin-example
    ./gradlew buildAndPushImage

Did I miss something?

**Comment by gamma** [comment]
Ok, it might some confusion on my side here ;)
It works as advertised ... but the thing that got me started is: I had an image

    registry:5000/my/image:latest

I build the new image - untagging the existing image to

    registry:5000/my/image:<none>

and having the "new" image

    my/image:latest

I was pretty sure that it behaved differently before ... did it not?

**Comment by gesellix** [comment]
Yeah, I guess that's an area where others are confused, too: There's actually no "untag" in Docker, but tags will be removed via `docker rmi ...` - which is a two step operation with:

- remove tag
- check whether "untagged" layers don't have any tag anymore, and if so, remove those layers, too.

So, setting a tag like `registry:5000/image:<none>` doesn't "free" the image from its tag.

The part with `registry:5000/` won't ever automatically be removed, especially not by tagging an image into `registry:5000/my/image:<none>`. So I guess that's another confusion on your side? ;-)

**Comment by gamma** [comment]
Uhm ... looks like a misunderstanding ...
The registry:5000 is not removed which is clear. The tag being "removed" is clear due to retagging the newly build image. What I was wondering about is that I end up with two images: the original one, being untagged now - and the new one without the repository part.

So:

  * I have an image in docker:
    * `repository:5000/my/image:latest` with hash (e.g.) `123456`
  * I run `DockerPublishTask`
  * I now have two images:
    * `repository:5000/my/image:<none>` with hash `123456`
    * `my/image:latest` with hash `654321` <-- the new one
  * But I expected to have only one image:
    * `repository:5000/my/image:latest` with hash `654321`

**Comment by gesellix** [comment]
Ah, alright. Can you tell me where the first images comes from? Did you manually create/tag it or did the plugin create it initially? I guess the plugin shouldn't touch the `<none>` on that image with hash `123456`.
The other new one with hash `654321` is kept for caching of subsequent builds, but maybe I should add some more documentation for such a behaviour.

**Comment by gamma** [comment]
Ok, that would make sense. I probably created the initial image by hand. Otherwise I would have stumbled over the current issues a lot earlier ;)

I checked my script again and changed it per your description. Unless you see something that is to be done, this issue can be closed.
