### ISSUE TITLE
Docker image is built locally even though remote dockerHost is set

### ISSUE THREAD

**Issue by grubers** [gesellix/gradle-docker-plugin#65]
I recently encountered an interesting behaviour when attempting to build docker images on a remote `dockerHost`. I noticed that I was able to build docker images on the remote docker host, even when the remote docker host was not reachable over the network. Further analysis revealed that the images were actually built locally. `dockerHost` was set correctly for `DockerBuildTask` in gradle (4.3.1). After digging deeper, I found out that a `DockerClientImpl` was supposedly being constructed with a correct `DockerEnv` (= remote docker host), but the `DockerClientConfig` within `DockerClientImpl` was wrong in the end (= local docker host). And this wrong `DockerClientConfig` was then being passed to `OkDockerClient` causing the images to be built locally instead of remotely.

The root cause seems to be the lines 152 - 154 in `DockerTask.groovy`:

```
dockerClient = new DockerClientImpl(
        env: dockerEnv,
        proxy: getProxy() ?: NO_PROXY)
```

As the return value of `getProxy()` is not strongly typed as `Proxy` the constructor

```
DockerClientImpl(DockerEnv env, Proxy proxy = NO_PROXY) {
    this(new DockerClientConfig(env), proxy)
}
```

is not called. Instead, the default constructor is called and, after construction, the properties `env` and `proxy` are set using reflection to call the setters. This behaviour is documented in the Groovy Style Guide (http://groovy-lang.org/style-guide.html) in chapter 8 ("Initializing beans with named parameters and the default constructor”):

> "You can use named parameters with the default constructor (first the constructor is called, then the setters are called in the sequence in which they are specified in the map)”.

As the `OkDockerClient` is initialized during the construction of `DockerClientImpl`, the value of `env` set later containing the remote docker host is never propagated to the `OkDockerClient` anymore. This leads to an inconsistent state: The `env` of `DockerClientImpl` contains the remote docker host but the `OkDockerClient` actually uses the local (default) docker host. The tricky part is that, often, building locally will also succeed and one does not notice that the image was not built remotely as intended.

One possible solution seems to be to not use the arguments map and explicitly cast the return value of `getProxy()`:

```
dockerClient = new DockerClientImpl(
        dockerEnv,
        (Proxy) getProxy() ?: NO_PROXY)
```

Could you look at and possibly verify this?

**Comment by grubers** [comment]
What a coincidence: I discovered and analyzed it two days ago, but just reported it before. It's a duplicate of https://github.com/gesellix/gradle-docker-plugin/issues/64 (reported yesterday) and resolved :)

**Comment by gesellix** [comment]
Hey, thanks for the detailed bug description and also for digging deep into the source code!
Yeah, coincidentally this bug has just been fixed and I also ensured that the relevant code path will handle both cases (dedicated constructor vs. named parameters) correctly.
Sorry for the inconvenience! :)
