### ISSUE TITLE
DockerContainerTask volumes doesn't work on Windows

### ISSUE THREAD

**Issue by ecsousa** [gesellix/gradle-docker-plugin#67]
DockerContainerTask checks that, in case of two ":", third part must be "ro"

However, on a Windows machine, volume instruction follows the pattern:

```
C:\path\to\dir:/path/to/dir
```

As we have two ":" chars on the string, `DockerContainerTask ` check fails although it shouldn't.

**Comment by gesellix** [comment]
Hey, that's probably a bit late, but I'd like to know whether you're working with LCOW or with Windows Containers. Your example would suggest the LCOW variant, correct?

**Comment by ecsousa** [comment]
Hi. I wasn't using LCOW at that time; it was the Docker for Windows, using standard Linux containers. But the fix should be the same, and paths formats are equal.

**Comment by gesellix** [comment]
Alright, then you might want to give the current release a try (in case you're still using it ;) ): https://plugins.gradle.org/plugin/de.gesellix.docker

Thanks for the quick feedback!
