### ISSUE TITLE
Multiple DockerPublishTask's in build file

### ISSUE THREAD

**Issue by witcold** [gesellix/gradle-docker-plugin#86]
Hi,

I'm trying to create two Gradle tasks to build Docker images for development and release purposes, so I came up with something like this:
```
task buildSnapshot(type: DockerPublishTask, dependsOn: 'jar') {
    imageName = "my-app"
    imageTag = "${version}-snapshot"
    buildContextDirectory = file("${buildDir}/${project.name}")
    authConfigPlain = getDockerClient().readAuthConfig(...)
    targetRegistries = [
            dev: "nexus-dc:443"
    ]
}

task buildRelease(type: DockerPublishTask, dependsOn: 'jar') {
    imageName = "my-app"
    imageTag = "${version}"
    buildContextDirectory = file("${buildDir}/${project.name}")
    authConfigPlain = getDockerClient().readAuthConfig(...)
    targetRegistries = [
            dev: "nexus-dc:443"
    ]
}
```

However, when I try to run `buildRelease` task, I get an image with `-snapshot` suffix. And vice versa, if I swap the tasks and run `buildSnapshot`, I will get an image without suffix.

I'm not sure if this is an issue with the plugin itself or rather with Gradle, but is there an ability to somehow limit the visibility of variables and have two tasks of the same type?

**Comment by gesellix** [comment]
This looks much like an issue with the plugin, I'll need to investigate.

**Comment by gesellix** [comment]
@witcold please give the new release `2020-10-03T11-49-08` a try. Thanks a lot for your bug report!
